version: "3.8"

services:
#  nginx:
#    build:
#      context: ./.docker/nginx
#    ports:
#      - 80:80
#      - 443:443
#    env_file: .env
#    volumes:
#      - ./.docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
#      - ./.docker/nginx/conf/upstream.conf:/etc/nginx/conf.d/upstream.conf
#      - ./.docker/nginx/sites-enabled:/etc/nginx/sites-enabled
#      - ./:/www/html
#    links:
#      - php

  database:
    build:
      context: ./.docker/database
    env_file: .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./.docker/database/data:/var/lib/mysql

  php:
    build:
      context: ./.docker/php
    env_file: .env
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - .:/var/www/html
#      - ./.docker/php/conf/project.pool.conf:/usr/local/etc/php-fpm.d/www.conf
#      - ./.docker/php/apache_config/httpd.conf:/etc/apache2/apache2.conf
      - ./.docker/php/apache_config/000-default.conf:/etc/apache2/sites-available/000-default.conf
    links:
      - database

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=database
    ports:
      - "5001:80"